#!/bin/bash
# homebrew update script to be run by chron and notify me if updates are available

# if brew exists on this system
if test -x /usr/local/bin/brew; then
  # notification center
  notifier=/usr/local/bin/terminal-notifier
  # update brew and find outdated packages
  updated=`/usr/local/bin/brew update 2>/dev/null | grep -i ^updated.*$`
  if [ ! -z "$updated" ]; then
    $notifier                 \
    -group cosine.brewupdate  \
    -title "homebrew updated" \
    -message "$updated"       \
    >/dev/null
  fi
  outdated=`/usr/local/bin/brew outdated 2>/dev/null | sort | tr '\n' ' '`
  if [ ! -z "$outdated" ]; then
    $notifier                           \
    -group cosine.brewupdate            \
    -title "homebrew packages outdated" \
    -message "$outdated"                \
    >/dev/null
  fi
fi
