#!/bin/bash

# michael cousins
# june 19, 2013
# shell script to copy my dotfiles to my home directory

# dotfile directory is this one
DOTLOC=~/dotfiles
DOTOLD=~/dotfiles_old
DOTNEW=~

# ignore these files
IGNORE=( README.md )

# make sure I want to copy new dotfiles in
echo -n "hey man. want some dotfiles? (y/n): "
read r
if [ $r ]
    then
    if [ ${r:0:1} == 'y' ] || [ ${r:0:1} == 'Y' ]
        then
        echo "i knew you were cool."

        # check for dotfiles_old directory
        if [ ! -d $DOTOLD ]
            then
            echo "creating folder for old dotfiles"
            mkdir $DOTOLD
        fi
        # save old dotfiles and symlink the new ones in
        echo "backing up old dotfiles to $DOTOLD and symlinking new ones to $DOTNEW"
        for f in $DOTLOC/*
        do
            # get filename
            FILE=`basename $f`
            IG=0
            # check if filename is in the ignore list
            for i in "${IGNORE[@]}"
            do
                if [ $FILE == $i ]
                    then
                    IG=1
                fi
            done
            # if not in the ignore list
            if [ $IG == 0 ]
                then
                THIS=`basename $0`
                # check to make sure the file is not this script
                if [ $FILE != $THIS ]
                    then
                    # check if this dotfile already exists and back it up
                    if [ -f DOTNEW/.$FILE ]
                        then
                        mv -f $DOTNEW/.$FILE $DOTOLD/.$FILE
                        echo "backed up .$FILE"
                    fi
                    # symlink the new one in
                    ln -sf $f $DOTNEW/.$FILE
                    echo "symlinked $FILE"
                fi
            fi
        done
    else
        echo "come back when you wanna have some fun."
    fi
else
    echo "what are you, a cop or something?"
fi
