#!/bin/bash
# update homebrew notify if upgrades are available

brew=/usr/local/bin/brew
notifier=/usr/local/bin/terminal-notifier

notify () {
  local title=$1
  local msg=$2

  if test -x $notifier; then
    $notifier -title "$title" -message "$msg"
  fi
}

update () {
  if test -x $brew; then
    updated=`$brew update 2>/dev/null | grep -i ^updated.*$`
    if [ ! -z "$updated" ]; then notify "homebrew updated" $updated; fi

    outdated=`$brew outdated 2>/dev/null | sort | tr '\n' ' '`
    if [ ! -z "$outdated" ]; then notify "packages outdated" $outdated; fi
  fi
}

update
